### PR TITLE
Changed the behaviour to slash command returning message attachments

### PR DESCRIPTION
**Pull request by Schoaf**
In order to be able to get Jira issue information in every channel (also private messages) I changed the behaviour to use a slash command that returns the original message and an attachment showing the Jira info. The message is posted with the same username and icon as the sender of the slash command.

### CODE REVIEW

**Comment by woutervb** [comment]
@Schoaf thanks for your work, looks nice. I don't have any working installation of mattermost anymore, so if interested you could take this project over

**Comment by Schoaf** [comment]
Hi. Sounds like a good idea. I'm not sure if we should keep those separate because they work differently (slash command vs. webhook) or if we should just merge it.

**Comment by woutervb** [comment]
When I started the slash command was not yet possible. So I went for the webhook. But personally I think the slash command is a better route.
I am working in an environment with hipchat connected to the jira instance. And there it works like the webhook, with as biggest impact that you can't even reference a ticket without the webhook interfering.

**Comment by Schoaf** [comment]
aha, I see. I didn't think of that yet. So it really seems to be the better approach to go via slash-command so the user can trigger the additional infos.  Okay, then I think it makes absolutely sense that we merge everything together.

**Pull request merged**
